/*
 * Copyright (C) 2006-2007  Gabriel Burca (gburca dash virtmus at ebixio dot com)
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

package com.ebixio.virtmus;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import org.openide.util.ImageUtilities;

/**
 *
 * @author  Gabriel Burca &lt;gburca dash virtmus at ebixio dot com&gt;
 */
public class About extends javax.swing.JPanel {
    Image splash;
    
    /** Creates new form NewJPanel */
    public About() {
        initComponents();
        
        // splash.gif in /branding/... gets saved as splash_virtmus.gif in the jar
        splash = ImageUtilities.loadImage("org/netbeans/core/startup/splash_virtmus.gif");
        
        int w = splash.getWidth(null);
        int h = splash.getHeight(null);
        this.setPreferredSize(new Dimension(w, h));
    }
    
    @Override
    public void paint(Graphics g) {
        g.drawImage(splash, 0, 0, null);
        g.setColor(Color.WHITE);
        g.drawString("VirtMus version " + MainApp.VERSION +
                "             For more information visit: http://virtmus.com/", 43, 30);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
